### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by YJNDL** [Infant83/VASPBERRY#10]
Can the author send a compiled version? Our server library doesn't seem to compile smoothly

**Comment by Infant83** [comment]
Hi, it would be also working with gfortran version.
Please have a try. Note that, however, with this version some functionality is limited as it has not been maintained.

**Comment by YJNDL** [comment]
Thank you for your wonderful code


But the result I will apply is not quite correct. Do we only need to do scf ？


Is it necessary to calculate the energy band after that?

**Comment by Infant83** [comment]
Please describe your error precisely. Input/output? I cannot figure out anything from your question. You can also read "README.md" file for some procedure.

**Comment by YJNDL** [comment]
Do I only need to follow the parameters once scf ？
 I did a self consistent calculation and  It's a little strange to find this result
I'm not sure whether the k-point setting method must be the same as yours
<img width="531" alt="1642509074(1)" src="https://user-images.githubusercontent.com/92591977/149937818-8c748448-243c-4508-b595-96354f63b1f6.png">
By the way, my compilation process was smooth, using the first compilation command

**Comment by YJNDL** [comment]
> 
At present, except for the kpoints difference, the calculation is designed according to your， But because MAGMOM  This parameter will report an error when I calculate. I annotate it to see if it has any impact

**Comment by Infant83** [comment]
> Do I only need to follow the parameters once scf ？
> I did a self consistent calculation and It's a little strange to find this result
> I'm not sure whether the k-point setting method must be the same as yours
> <img alt="1642509074(1)" width="531" src="https://user-images.githubusercontent.com/92591977/149937818-8c748448-243c-4508-b595-96354f63b1f6.png">
> By the way, my compilation process was smooth, using the first compilation command

No, you can specify your own k-grid according to your system. But due to some symmetry, the gamma centered or gamma off kind of setting should be correctly applied according tor your lattice system. 
I cannot give you exact answer before seeing your band structure and poscar etc. Anyway but, you may know what to do, though.

**Comment by YJNDL** [comment]
OK, thank you for your help
 Can you answer me a question?
  This is the picture we drew by hand. Must it be able to form a hexagonal structure in the end?
 Because the structure you gave can finally draw a hexagonal repeating unit, and so can the magnification rate in many literatures. Do you think the strip structure I drew is unreasonable

**Comment by Infant83** [comment]
> OK, thank you for your help
> Can you answer me a question?
> This is the picture we drew by hand. Must it be able to form a hexagonal structure in the end?
> Because the structure you gave can finally draw a hexagonal repeating unit, and so can the magnification rate in many literatures. Do you think the strip structure I drew is unreasonable

Well, if your lattice is hexagonal, then the BZ would be also hexagonal. I do not know your structural details. So I cannot give you my answer unless you give me some information about the lattice. For the extended draw of your BZ, you can put -kp option. Have a try with "-kp 2".

**Comment by YJNDL** [comment]
OK, thank you very much for your reply. Then  the number of band  have any requirements?
