### ISSUE TITLE
vaspberry

### ISSUE THREAD

**Issue by Nityasagar** [Infant83/VASPBERRY#2]
Dear Hyun-Jung Kim,
Many thanks for this awesome code and example. Could you kindly suggest me, how can we get spin-Berry curvature? Can we make a 1D and 3D plot option in the BZ?
2. The code automatically takes the number of valence bands (s) to Compute the Chern number., how can we select certain no. of bands?
I am also interested to compute the Circular dichroism (optical selectivity response to the circularly polarized light) and Wavefunction plot (at Gamma point only ), but not getting how to do this. Could you kindly tell us, how can we do this?

I am also excited to see your examples on Quantum Anomalous Hall effect feature. Please provide the same.
May I request your email address to share some of my calculation files?
Best wishes. Many thanks.
Nitya
nityasagar.ph14216@inst.ac.in

**Comment by Infant83** [comment]
responsed via private e-mail.
