### ISSUE TITLE
Problem with berry curvature on a magnetically doped surface

### ISSUE THREAD

**Issue by anhph** [Infant83/VASPBERRY#3]
Hi,

I'm trying to calculate the Berry curvature on a ferromagnetically magnetically doped surface (slab structure) with spin-orbit, but I have been getting this error !!! ne(K) /= ne(K') !!!  
Any help would be appreciated. 
Thanks,
Anh

**Comment by Infant83** [comment]
I think this is because your system is "probably" metallic. 
You may specify the number of electrons in your system by hand adding "-ne" option into your command line.
Have a look the help page first, by -h option.
