### ISSUE TITLE
Adjust Fermi level

### ISSUE THREAD

**Issue by SimonMel** [Infant83/VASPBERRY#5]
In order to calculate Berry curvature for different Fermi level values, should one vary the band range with -ii x -if y, or should one adjust the number of electrons with -ne?

**Comment by Infant83** [comment]
One can change with -ne but, in this case, it should be an integer.
You can also investigate a certain range of eigenvalues -ii and -if, and in this case, -ne does not have meaning in the code.
Are you considering some partial number of the additional electron is added/extracted cases?
