### ISSUE TITLE
Can we caculate berry phase of single band? 

### ISSUE THREAD

**Issue by X-T-Zeng** [Infant83/VASPBERRY#7]
Dear Hyun-Jung Kim,
 is there a solution to caculate wilson loop, since it is really important for topological matter.

**Comment by Infant83** [comment]
Hi, this program does not provide solution for Wilson loop calculations. You may check wannier_tools for that. http://www.wanniertools.com

**Comment by X-T-Zeng** [comment]
Thanks for your solution!
&nbsp;

hjk


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hyun-Jung Kim"<notifications@github.com&gt;; 
发送时间: 2020年12月3日(星期四) 晚上9:10
收件人: "Infant83/VASPBERRY"<VASPBERRY@noreply.github.com&gt;; 
抄送: ":うずまきナ"<383793132@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [Infant83/VASPBERRY] Can we caculate berry phase of single band?  (#7)





 
Hi, this program does not provide solution for Wilson loop calculations. You may check wannier_tools for that. http://www.wanniertools.com
