### ISSUE TITLE
regarding berry curvature calculations

### ISSUE THREAD

**Issue by Son123K** [Infant83/VASPBERRY#9]
Dear Hyun-Jung Kim,

Thanks for this wonderful code.
I need to calculate the Berry curvature along high symmetry path, but the WAVECAR calculated using the high symmetry kpath is giving me this error while running the code:
##############################################################################
forrtl" severe(25): record number outside range, unit 10..........
##############################################################################
whereas the code is working fine with uniform kmesh used for the calculations to generate WAVECAR. Any help regarding this would be highly appreciated.

Best regards.
Sonali
sonalikakkar12@gmail.com

**Comment by Infant83** [comment]
To calculate berry curvature along high symmetry path, please use "-kubo 1" option.

**Comment by Son123K** [comment]
Thank you so much for your kind response.

-------
Sonali Kakkar
PhD research scholar
Institute of Nanoscience and Technology (INST)
Mohali, Punjab-160062,India
Email: ***@***.***

**Comment by Nick12-hub** [comment]
> To calculate berry curvature along high symmetry path, please use "-kubo 1" option.

Are you main enter ./vaspberry -kubo 1 ? It seems non-work. or just replace the KPOINTS file with high symmetry path of M->K->G->K->M for a calcution again? Hope for your reply, Thank you!

**Comment by Infant83** [comment]
Yes, for the k-path, you need to calculate with the WAVECAR after the band structure calculations. The example is uploaded in the 1H-MoS2/KPATH folder for this case.

**Comment by Son123K** [comment]
Thank you so much for the clarification. I have another query:
Can we calculate anomalous Hall conductivity with this code? If Yes, how
can we do that?
Your response will be highly appreciated.

Regards.
-------
Sonali Kakkar
PhD research scholar
Institute of Nanoscience and Technology (INST)
Mohali, Punjab-160062,India
Email: ***@***.***

**Comment by Son123K** [comment]
I have calculated the berry curvature using the WAVECAR of band
calculations but I am not getting the periodic berry curvature. The
corresponding plot is attached along with. Could you please have a look and
can tell me what mistake I am making? Your suggestion is highly welcome.
Please ask for anything if you need any input file. I will be grateful to
you.

Regards.
-------
Sonali Kakkar
PhD research scholar
Institute of Nanoscience and Technology (INST)
Mohali, Punjab-160062,India
Email: ***@***.***

**Comment by Infant83** [comment]
Dear Sonali,

I cannot get your attached file but I just assume that you have 
obtain the repeated images of the plot and the result looks messed up 
over the BZ.
This is due to the plot is artificially multiplied with -kp 2 option (by default) 
and the results are sorted over the BZ. This happens since the code is 
written to deal with the berry curvature over the 2D BZ and to draw the figure 
smoothly I have set it to be sorted over the BZ when the result is written.

But now, we are dealing with the k-path mode (kline mode with KPOINTS file),
I have slightly changed the code to meet the purpose.

The solution is to give -kubo 2 option instead of 1 and -kp 1 option instead of -kp 2 (default value).
The updated result is presented in the 1H-MoS2/KPATH/3.BC_kubo folder and the source code is 
also updated according to the changes. Please download the new version and check it.

Thank you very much for letting me know the issue and make it possible to update it.
Sincerely
Hyun-Jung


___________________________________________
Hyun-Jung Kim, Ph. D. 
Peter Grünberg Institut (PGI-1) and 
Institute for Advanced Simulation (IAS-1)
Forschungszentrum Jülich, 52428 Jülich, Germany
–––––––––––––––––––––––––––––––––––––––––––
Office: Room 110, Bldg. 04.12.
Phone (office) : +49 2461 61-1719
Phone : 0160 98722693
Publication list: google.scholar <http://scholar.google.com/citations?user=FtSLeT4AAAAJ&hl=en> 
–––––––––––––––––––––––––––––––––––––––––––

**Comment by YJNDL** [comment]
Thanks for your code first
There seems to be a problem when I use it
(base) [zyl@login 1.scf]$ ./vaspberry -kx 12 -ky 12 -ii 1 -if 18
Segmentation fault (core dumped)
Hope for your reply, Thank you!

**Comment by YJNDL** [comment]
even when I only use ./vaspberry 
this error still exist

**Comment by Infant83** [comment]
> Thanks for your code first
> There seems to be a problem when I use it
> (base) [zyl@login 1.scf]$ ./vaspberry -kx 12 -ky 12 -ii 1 -if 18
> Segmentation fault (core dumped)
> Hope for your reply, Thank you!

In what kind of situation this error happened? 
It would be much better that you show your details. 
Is your system spin-orbit coupling turned on? Then please put "-s 2" option.
Is your k-point grid is really 12x12 and your EIGENVAL contains 144 k-points explicitly? 
Make sure that you have to run vasp scf calculation first with ISYM -1 to get full BZ information for the WAVECAR.

**Comment by YJNDL** [comment]
> > Thanks for your code first
> > There seems to be a problem when I use it
> > (base) [zyl@login 1.scf]$ ./vaspberry -kx 12 -ky 12 -ii 1 -if 18
> > Segmentation fault (core dumped)
> > Hope for your reply, Thank you!
> 
> In what kind of situation this error happened? It would be much better that you show your details. Is your system spin-orbit coupling turned on? Then please put "-s 2" option. Is your k-point grid is really 12x12 and your EIGENVAL contains 144 k-points explicitly? Make sure that you have to run vasp scf calculation first with ISYM -1 to get full BZ information for the WAVECAR.

maybe I know what happened 
by the way
when I setup this program
the command which I use is 
mpiifort -fpp -assume byterecl -mkl -shared -fPIC -o vaspberry vaspberry.f
if I use the commond you say
I will get the 'mpif.h' can not be open
may something worry

**Comment by YJNDL** [comment]
![1638551365(1)](https://user-images.githubusercontent.com/92591977/144643861-35bbf431-72e5-4684-ba4b-f64cd01c9990.png)
![1638551424(1)](https://user-images.githubusercontent.com/92591977/144644005-f5abb453-9c60-479f-b222-458c290fef6f.png)
this is my situation

**Comment by YJNDL** [comment]
![1638556518(1)](https://user-images.githubusercontent.com/92591977/144655013-4649ed37-f711-45c1-a6d4-7725d874ab61.png)
after I did scf
I will meet this problem
![1638556669](https://user-images.githubusercontent.com/92591977/144655277-8c4909bb-8b41-4be9-8b7e-54e8734b2163.png)

**Comment by Infant83** [comment]
How did you compile your code?

Is the library properly linked?

It is rather strange that even the -h option doesn’t work.

mpif90 -DMPI_USE -mkl -fpp -assume byterecl -o vaspberry vaspberry.f

if your compiler “mpif90” is built with ifort, then this will be no problem.
The MKL can be installed along with intel oneAPI for free (i guess) as well as fortran compiler.

If it is not related with this problem, 
I actually have no idea what happened to your system. 

Did you downloaded the recent version of vaspberry.f ? 
The most recent version is modified at 30.Nov.2021.
Please have a check.

Sincerely,
Hyun-Jung

**Comment by Infant83** [comment]
Ah... you have already tried with "mpiifort -fpp -assume byterecl -mkl -shared -fPIC -o vaspberry vaspberry.f"
Then, you get some error message from mpi related thing. 
I just assume that you have broken some link to your mpi library for some reason. 
You may consult to your system manager. I have acually no idea about your system configurations... I'm sorry for that.

**Comment by YJNDL** [comment]
> Ah... you have already tried with "mpiifort -fpp -assume byterecl -mkl -shared -fPIC -o vaspberry vaspberry.f" Then, you get some error message from mpi related thing. I just assume that you have broken some link to your mpi library for some reason. You may consult to your system manager. I have acually no idea about your system configurations... I'm sorry for that.

this commond can successfully run
but as I use ./vaspberry -h
![image](https://user-images.githubusercontent.com/92591977/144695008-b7d956af-1e23-4857-8903-c370d6791cb2.png)

**Comment by YJNDL** [comment]
> mpif90 -DMPI_USE -mkl -fpp -assume byterecl -o vaspberry vaspberry.f

if I use this commond
![1638587786(1)](https://user-images.githubusercontent.com/92591977/144695059-5f5c6d95-eea8-41d2-8c3c-21d717e0f5f7.jpg)

**Comment by YJNDL** [comment]
> Ah... you have already tried with "mpiifort -fpp -assume byterecl -mkl -shared -fPIC -o vaspberry vaspberry.f" Then, you get some error message from mpi related thing. I just assume that you have broken some link to your mpi library for some reason. You may consult to your system manager. I have acually no idea about your system configurations... I'm sorry for that.

mpiifort -fpp -assume byterecl -mkl -shared -fPIC -o vaspberry vaspberry.f
The code can be successfully implemented
but as I use ./vaspberry -h
![1638587666(1)](https://user-images.githubusercontent.com/92591977/144695121-698f4238-135e-462c-8d60-d61ce2623ef2.png)

**Comment by YJNDL** [comment]
> Ah... you have already tried with "mpiifort -fpp -assume byterecl -mkl -shared -fPIC -o vaspberry vaspberry.f" Then, you get some error message from mpi related thing. I just assume that you have broken some link to your mpi library for some reason. You may consult to your system manager. I have acually no idea about your system configurations... I'm sorry for tha
The code can be successfully implemented by this commond mpiifort -fpp -assume byterecl -mkl -shared -fPIC -o vaspberry vaspberry.f
but as I use ./vaspberry -h
![1638588024(1)](https://user-images.githubusercontent.com/92591977/144695163-e7fcb65f-a2e3-4c54-9c4e-0e5e2869993d.png)

**Comment by YJNDL** [comment]
![1638589502(1)](https://user-images.githubusercontent.com/92591977/144695743-7ad918a6-8684-48b1-93cd-ba6ff6a6df57.png)
this is the error

**Comment by Infant83** [comment]
> > mpif90 -DMPI_USE -mkl -fpp -assume byterecl -o vaspberry vaspberry.f
> 
> if I use this commond ![1638587786(1)](https://user-images.githubusercontent.com/92591977/144695059-5f5c6d95-eea8-41d2-8c3c-21d717e0f5f7.jpg)

I think, your mpif90 is not compiled with intel ifort, instead, it is binded with gfortran. For the gfortran, the current version only supports serial version and it is not maintained anymore. You can compile vaspberry_gfortran_serial.f.

**Comment by Infant83** [comment]
You need to link lapack and include file properly when using gfortran version.

**Comment by Son123K** [comment]
Thank you so much for your kind reply. I am running the code as per
instructions, but the output file is not written in the working folder. I
am unable to locate the output file. Earlier, it was written in the working
folder only. Any kind of help regarding this will be highly appreciated.

-------
Sonali Kakkar
PhD research scholar
Institute of Nanoscience and Technology (INST)
Mohali, Punjab-160062,India
Email: ***@***.***

**Comment by Infant83** [comment]
Dear Sonali,

well, I cannot get your problem.
Please let me know more clear, 
0. did the compilation successful?
1. what did you do then?
2. what was the output during the run?
3. input / output ?

Thank you.
Sincerely,

___________________________________________
Hyun-Jung Kim, Ph. D. 
Peter Grünberg Institut (PGI-1) and 
Institute for Advanced Simulation (IAS-1)
Forschungszentrum Jülich, 52428 Jülich, Germany
–––––––––––––––––––––––––––––––––––––––––––
Office: Room 110, Bldg. 04.12.
Phone (office) : +49 2461 61-1719
Phone : 0160 98722693
Publication list: google.scholar <http://scholar.google.com/citations?user=FtSLeT4AAAAJ&hl=en> 
–––––––––––––––––––––––––––––––––––––––––––

**Comment by Son123K** [comment]
0. Well, the output message is saying that it is successful.
2. The output is attached as screenshot here with. Although in the attached
screenshot, it is saying "Results are summarized in BERRYCURV.dat", I don't
see any such file in the working folder.
3. Input:  vaspberry -kx 12 -ky 12 -is 292 -kubo 2 -kp 1 -ne 292

Kindly let me know if any more detail is required.Thanks for your patience.

-------
Sonali Kakkar
PhD research scholar
Institute of Nanoscience and Technology (INST)
Mohali, Punjab-160062,India
Email: ***@***.***

**Comment by Infant83** [comment]
Dear Sonali,

For -kubo 2 option, you don’t need to specify -kx nor -ky. 
Anyway, it is strange. 
For my case, it generate BERRYCURV_KUBO.dat file.

I would try
./vaspberry -kubo 2 -is 292 -ne 292

Did you try with the newer version from the git?

Sincerely,
Hyun-Jung

**Comment by Son123K** [comment]
Thanks for your reply. I tried with newer version also, but I am getting
this problem. Kindly look into the issue.

----------
Sonali Kakkar
PhD research scholar
Institute of Nanoscience and Technology(INST)
Mohali, Punjab -160062,India
Email: ***@***.***

**Comment by Infant83** [comment]
did you compiled vaspberry_gfortran_serial.f ??

If not, please give me your input and output so that I can check it up. 
I do not get what would be the source of error at this moment.

**Comment by Son123K** [comment]
Greetings!!!!

Your earlier response is indeed helpful. Thanks a ton for the same. Kindly
help me regarding the calculation of anomalous Hall conductivity using
vaspberry code. It will be really appreciated.

Regards.
-------
Sonali Kakkar
PhD research scholar
Institute of Nanoscience and Technology (INST)
Mohali, Punjab-160062,India
Email: ***@***.***

**Comment by Son123K** [comment]
Dear Hyun-Jung Kim,

Thanks a lot for your earlier help with the VASPBERRY code for Berry
curvature calculations. I have one more issue. Is the Chern number
mentioned in the BERRYCURV_KUBO.EIG-n.dat file gives the value of Chern
number for the nth band? Or, the Chern number mentioned in the
BERRYCURV_KUBO.dat file gives the total value of Chern number for all the
bands considered? If not, what is the standard procedure to calculate Chern
number? Could you please elaborate a little.

With Best Regards.
-------
Sonali Kakkar
PhD research scholar
Institute of Nanoscience and Technology (INST)
Mohali, Punjab-160062,India
Email: ***@***.***

**Comment by Infant83** [comment]
Dear Sonali,

Sorry for the late reply.
I was bit off from the VASPBERRY these days, and research itself as well…

By the way, regarding the question about KUBO related values, it is only intended for the berry curvature (BC) calculation, 
not for the Chern number which is the integration over the k-space.
As you already noticed, the BC values from KUBO only represents the value at the spot (k-point), 
not for the encircled area of small patches where Fukui’s method does.

Hence, if you want to get Chern number for a specific band, 
you have to make sure that the state you are interested in is nicely isolated (no band crossings with other bands)
over the brillouin zone, and apply Fukui’s scheme to get Chern number.
This will result it some integer value of Chern number.

Hope this helps.
Sincerely,

Hyun-Jung

**Comment by JohnsonLee1999** [comment]
Dear Hyun-Jung Kim:

I hope this message finds you well.

I am writing to inquire about the capabilities of the latest version of the VASPBERRY code. Specifically, I am interested in knowing whether the code is equipped to perform calculations for bulk materials.

Could you kindly provide some insight into this matter? Any information or guidance you could offer would be greatly appreciated.

Thank you very much for your time and assistance.

Warm regards,

Li Peixuan
